version: "2.1"
services:
  kube-compose:
    build:
      context: .
      dockerfile: Dockerfile
    image: kube-compose:latest
    network_mode: host
    volumes:
    - ./test:/app/test:rw
    working_dir: /app/test
