version: "2.1"
services:
  jompose:
    build:
      context: .
      dockerfile: Dockerfile
    image: jompose:latest
    network_mode: host
    volumes:
    - ./test:/app/test:rw
    working_dir: /app/test
