apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment --file docker-compose.yml
      --file docker-compose.override.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: authentication-service
  name: authentication-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: authentication-service
status:
  loadBalancer: {}
